from .activity import *
from .activityList import *
from .admin import *
from .adminList import *
from .colour import *
from .edit import *
from .help import *
from .kill import *
from .new import *
from .notify import *
from .reaction import *
from .removeAdmin import *
from .restart import *
from .rmActivity import *
from .systemChannel import *
from .update import *
from .version import *
from .welcomeChannel import *
